### ISSUE TITLE
Put var name before type in catalogue

### ISSUE THREAD

**Issue by danielcompton** [cljsinfo/api-refs#52]
Nice work on this, it looks really good! I think it might be easier for people to read if the var name was first, and then the type came after it? It makes scanning easier. I'm happy to put together a PR for this if I can find the right spot.

**Comment by shaunlebron** [comment]
you mean placing the type column after the var column in the reference table?

**Comment by danielcompton** [comment]
Yep

**Comment by shaunlebron** [comment]
catalog branch is updated, thanks again
