### ISSUE TITLE
Dash.app docset

### ISSUE THREAD

**Issue by shaunlebron** [cljsinfo/api-refs#53]
@jwr suggests creating a [Dash.app docset](https://kapeli.com/docsets).  pull requests welcome for this

**Comment by shaunlebron** [comment]
ideas to create simplest stopgap docset from our markdown files:

- name: ClojureScript
- logo: cljs logo
- index: grip-generated html from README.md
  - no table of contents
- sections: library api section, and compiler api section (links to index anchors)
  - entry type: Section
- namespaces: links to index anchors
  - entry type: Namespace
- symbols: full names with ns, as links to grip-generated html files from ref/*.md
  - entry type: Function, Macro, Variable, Protocol, Type, (and Special Form which I emailed for inclusion)

**Comment by shaunlebron** [comment]
documented how to build it here:
https://github.com/cljsinfo/api-refs#dash-docset

will create new issue to track publishing to Dash

**Comment by jwr** [comment]
This is great, thanks! One thing, though: does the docset have any control over how search results are ordered? Currently searching for "map" shows IMap and ITransientMap protocols as two first results, which is likely not what the user was looking for. I am not sure if that is a docset thing or not.

**Comment by shaunlebron** [comment]
Good catch.  Searching for `/map` gives close to the results that we would expect from the Clojure docset. The problem is that I'm including the namespace in all the search keys, and it's throwing off the search priority.  I guess it depends on whether we want to see namespaces in the search results or not:

<img src="https://cloud.githubusercontent.com/assets/116838/7855059/4a95d91c-04e4-11e5-92c9-f2b6940bf60d.png" width="300px"> <img src="https://cloud.githubusercontent.com/assets/116838/7855060/4a9618d2-04e4-11e5-8cd5-b23edb6ad6df.png" width="300px">

**Comment by jwr** [comment]
I'd drop the namespace if it were up to me. It is often confusing (why do map-invert or rename-keys live in clojure.set anyway?) and I think it doesn't bring much value in Dash searches, where you want to get to a specific function in a matter of seconds.

**Comment by shaunlebron** [comment]
agreed, moved to #58

**Comment by shaunlebron** [comment]
looks good now
![screen shot 2015-05-28 at 12 33 08 pm](https://cloud.githubusercontent.com/assets/116838/7866541/ce433f06-0535-11e5-9f5d-32f73d5a2ffe.png)

**Comment by jwr** [comment]
Yup, that looks great.
